Repository contentauth/c2pa-rs, pull requests merged in 2025-10, with the labels that each got.

#1427 fix: mark `DigitalSourceType` fields as deprecated without warning (new serde update)
  sdk/Cargo.toml
  sdk/src/assertions/actions.rs
Labels: safe to test

#1470 chore: Fix format
  sdk/src/claim.rs
Labels: safe to test, check-release

#1468 chore: release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  c2pa_c_ffi/CHANGELOG.md
  c2pa_c_ffi/Cargo.toml
  cli/CHANGELOG.md
  cli/Cargo.toml
  make_test_images/Cargo.toml
Labels: release

#1472 build: Update httpmock to 0.8.0
  Cargo.lock
  cli/Cargo.toml
  deny.toml
  sdk/Cargo.toml
Labels: safe to test

#1480 docs: fix docs.rs build by removing removed features
  sdk/src/lib.rs
Labels: safe to test
