Repository contentauth/c2pa-rs, pull requests merged in 2025-08, with the labels that each got.

#1278 chore: update ureq
  Cargo.lock
  sdk/Cargo.toml
  sdk/examples/v2show.rs
  sdk/src/crypto/ocsp/fetch.rs
  sdk/src/crypto/time_stamp/error.rs
  sdk/src/crypto/time_stamp/http_request.rs
  sdk/src/settings/mod.rs
  sdk/src/settings/signer.rs
  sdk/src/store.rs
Labels: safe to test

#1266 feat: V2 Claims are now generated by default
  .github/workflows/ci.yml
  Cargo.lock
  c2pa_c_ffi/src/c_api.rs
  c2pa_c_ffi/src/error.rs
  cli/sample/test.json
  cli/tests/fixtures/ingredient_test.json
  make_test_images/Cargo.toml
  make_test_images/json_manifests_v2/C.json
  make_test_images/json_manifests_v2/CA.json
  make_test_images/json_manifests_v2/CACA.json
  make_test_images/json_manifests_v2/CACAE-uri-CA.json
  make_test_images/json_manifests_v2/CACAICAICICA.json
  make_test_images/json_manifests_v2/CAE-uri-CA.json
  make_test_images/json_manifests_v2/CAI.json
  make_test_images/json_manifests_v2/CAIAIIICAICIICAIICICA.json
  make_test_images/json_manifests_v2/CAICA.json
  make_test_images/json_manifests_v2/CAICAI.json
  make_test_images/json_manifests_v2/CI.json
  make_test_images/json_manifests_v2/CICA.json
  make_test_images/json_manifests_v2/CICACACA.json
  make_test_images/json_manifests_v2/CIE-sig-CA.json
  make_test_images/json_manifests_v2/CII.json
  make_test_images/json_manifests_v2/E-sig-CA.json
  make_test_images/json_manifests_v2/E-uri-CA.json
  make_test_images/json_manifests_v2/XCA.json
  make_test_images/json_manifests_v2/XCI.json
  make_test_images/src/make_test_images.rs
  sdk/examples/c2pa.toml
  sdk/src/assertions/actions.rs
  sdk/src/assertions/ingredient.rs
  sdk/src/builder.rs
  sdk/src/claim.rs
  sdk/src/error.rs
  sdk/src/identity/tests/claim_aggregation/validation.rs
  sdk/src/ingredient.rs
  sdk/src/lib.rs
  sdk/src/manifest.rs
  sdk/src/manifest_store.rs
  sdk/src/reader.rs
  sdk/src/resource_store.rs
  sdk/src/settings/builder.rs
  sdk/src/status_tracker/mod.rs
  sdk/src/store.rs
  sdk/src/validation_results.rs
  sdk/tests/fixtures/manifest.json
  sdk/tests/fixtures/test_settings.toml
  sdk/tests/integration.rs
  sdk/tests/known_good/CA_test.json
  sdk/tests/test_builder.rs
Labels: needs-doc

#1287 fix: Enable additional features on c2pa-c-ffi
  c2pa_c_ffi/Cargo.toml
Labels: safe to test

#1258 feat: Add metadata assertion and support for validation
  sdk/src/assertions/labels.rs
  sdk/src/assertions/metadata.rs
  sdk/src/assertions/mod.rs
  sdk/src/builder.rs
  sdk/src/claim.rs
  sdk/tests/integration.rs
  sdk/tests/v2_api_integration.rs
Labels: safe to test

#1306 feat: Add new soft binding fields to the ingredient assertion structure
  sdk/src/assertions/ingredient.rs
Labels: safe to test

#1220 fix: Same file sign
  cli/src/main.rs
  cli/tests/integration.rs
Labels: safe to test

#1303 chore: release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  c2pa_c_ffi/CHANGELOG.md
  c2pa_c_ffi/Cargo.toml
  cli/CHANGELOG.md
  cli/Cargo.toml
  make_test_images/Cargo.toml
Labels: release

#1318 chore: release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  c2pa_c_ffi/CHANGELOG.md
  c2pa_c_ffi/Cargo.toml
  cli/CHANGELOG.md
  cli/Cargo.toml
  make_test_images/Cargo.toml
Labels: release

#1312 fix: Fix a regression for invalid manifest handling and reader creation
  c2pa_c_ffi/src/c_api.rs
  sdk/examples/v2api.rs
  sdk/src/reader.rs
  sdk/tests/fixtures/adobe-20220124-E-clm-CAICAI.jpg
  sdk/tests/known_good/C.json
  sdk/tests/known_good/CA.json
  sdk/tests/known_good/XCA.json
Labels: safe to test

#1332 fix: ingredient thumbnail generation respect settings
  sdk/src/ingredient.rs
Labels: safe to test

#1340 style: fix docs and dead code lint
  sdk/src/ingredient.rs
  sdk/src/utils/thumbnail.rs
Labels: safe to test

#1341 feat(sdk): falls back to fs for large intermediate streams
  Cargo.lock
  sdk/Cargo.toml
  sdk/src/settings/mod.rs
  sdk/src/store.rs
  sdk/src/utils/io_utils.rs
Labels: safe to test

#1335 chore: release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  c2pa_c_ffi/CHANGELOG.md
  c2pa_c_ffi/Cargo.toml
  cli/CHANGELOG.md
  cli/Cargo.toml
  make_test_images/Cargo.toml
Labels: release

#1343 fix: removes asm feature for sha2
  Cargo.lock
  sdk/Cargo.toml
  sdk/src/utils/thumbnail.rs
Labels: safe to test, check-release

#1350 chore(sdk): enable asm optimizations for sha2 on aarch64
  Cargo.lock
  sdk/Cargo.toml
Labels: safe to test, check-release
