Repository contentauth/c2pa-rs, pull requests merged in 2025-03, with the labels that each got.

#965 fix: Fix incorrect calculation for the reserved size
  internal/crypto/src/raw_signature/openssl/signers/ecdsa_signer.rs
  internal/crypto/src/raw_signature/openssl/signers/ed25519_signer.rs
  internal/crypto/src/raw_signature/openssl/signers/rsa_signer.rs
  internal/crypto/src/raw_signature/rust_native/signers/ecdsa_signer.rs
  internal/crypto/src/raw_signature/rust_native/signers/ed25519_signer.rs
  internal/crypto/src/raw_signature/rust_native/signers/rsa_signer.rs
Labels: bug, In Code Review, accepted

#968 fix: ISSUE-967: Remove the `RST0..=RST7` check from the `has_length` method for the JPEG asset handler.
  sdk/src/asset_handlers/jpeg_io.rs
Labels: safe to test

#966 chore: release
  CHANGELOG.md
  Cargo.lock
  cawg_identity/CHANGELOG.md
  cawg_identity/Cargo.toml
  cli/CHANGELOG.md
  cli/Cargo.toml
  internal/crypto/CHANGELOG.md
  internal/crypto/Cargo.toml
  internal/status-tracker/CHANGELOG.md
  internal/status-tracker/Cargo.toml
  sdk/Cargo.toml
Labels: release

#984 chore: release
  CHANGELOG.md
  Cargo.lock
  cawg_identity/CHANGELOG.md
  cawg_identity/Cargo.toml
  cli/CHANGELOG.md
  cli/Cargo.toml
  sdk/Cargo.toml
Labels: release

#986 feat: adds allActionsIncluded flag to Actions Assertion
  sdk/src/assertions/actions.rs
Labels: safe to test

#988 chore(c2pa): release v0.48.0
  CHANGELOG.md
  Cargo.lock
  cawg_identity/Cargo.toml
  cli/Cargo.toml
  sdk/Cargo.toml
Labels: release

#989 fix(c2patool): fixes crash and improves cawg support
  Cargo.lock
  cawg_identity/Cargo.toml
  cli/Cargo.toml
  cli/src/main.rs
  cli/tests/fixtures/C_with_CAWG_data.jpg
  cli/tests/integration.rs
  internal/crypto/Cargo.toml
  sdk/Cargo.toml
  sdk/src/reader.rs
Labels: safe to test

#990 chore(c2pa): release v0.48.1
  CHANGELOG.md
  Cargo.lock
  cawg_identity/Cargo.toml
  cli/Cargo.toml
  sdk/Cargo.toml
Labels: release

#992 chore: publish c2patool and cawg_identity updates
  Cargo.lock
  cawg_identity/Cargo.toml
  cli/Cargo.toml
  sdk/Cargo.toml
Labels: safe to test

#995 chore: release
  CHANGELOG.md
  Cargo.lock
  cawg_identity/CHANGELOG.md
  cawg_identity/Cargo.toml
  cli/CHANGELOG.md
  cli/Cargo.toml
  internal/crypto/CHANGELOG.md
  internal/crypto/Cargo.toml
  sdk/Cargo.toml
Labels: release
