Repository contentauth/c2pa-rs, pull requests merged in 2025-02, with the labels that each got.

#903 docs: Fix reported errors for docs
  Cargo.lock
  Makefile
  cli/Makefile
  cli/src/main.rs
  cli/src/signer.rs
  sdk/src/assertions/actions.rs
  sdk/src/jumbf_io.rs
  sdk/src/reader.rs
  sdk/src/validation_status.rs
Labels: safe to test

#904 feat: WIP branch for reading cawg data
  Cargo.lock
  Makefile
  cawg_identity/src/claim_aggregation/ica_signature_verifier.rs
  cawg_identity/src/claim_aggregation/w3c_vc/did_web.rs
  cawg_identity/src/claim_aggregation/w3c_vc/serialization.rs
  cli/Cargo.toml
  cli/src/main.rs
  cli/tests/fixtures/C_with_CAWG_data.jpg
  sdk/Cargo.toml
  sdk/src/error.rs
  sdk/src/hashed_uri.rs
  sdk/src/manifest_store.rs
  sdk/src/reader.rs
Labels: safe to test

#899 chore: release
  CHANGELOG.md
  Cargo.lock
  cawg_identity/Cargo.toml
  cli/Cargo.toml
  internal/crypto/CHANGELOG.md
  internal/crypto/Cargo.toml
  internal/status-tracker/CHANGELOG.md
  internal/status-tracker/Cargo.toml
  sdk/Cargo.toml
Labels: release

#909 feat: c2patool to read cawg data with `--detailed` flag too
  cli/src/main.rs
Labels: safe to test

#916 chore: release
  CHANGELOG.md
  Cargo.lock
  cawg_identity/CHANGELOG.md
  cawg_identity/Cargo.toml
  cli/CHANGELOG.md
  cli/Cargo.toml
  sdk/Cargo.toml
Labels: release

#919 chore(cawg-identity): release v0.7.0
  Cargo.lock
  cawg_identity/CHANGELOG.md
  cawg_identity/Cargo.toml
Labels: release

#921 chore(cawg-identity): release v0.8.0
  Cargo.lock
  cawg_identity/CHANGELOG.md
  cawg_identity/Cargo.toml
Labels: release

#864 fix: Use correct byte label for GIF Plain Text Extension
  sdk/src/asset_handlers/gif_io.rs
Labels: bug, accepted

#927 chore: release
  CHANGELOG.md
  Cargo.lock
  cawg_identity/CHANGELOG.md
  cawg_identity/Cargo.toml
  cli/Cargo.toml
  sdk/Cargo.toml
Labels: release
