Repository contentauth/c2pa-rs, pull requests merged in 2025-05, with the labels that each got.

#722 feat: SVG thumbnails with a fix to the ingredient thumbnail format detection
  sdk/src/assertions/labels.rs
  sdk/src/ingredient.rs
Labels: enhancement, accepted, safe to test

#1093 chore: Allow new license
  deny.toml
Labels: safe to test

#1095 chore: release
  CHANGELOG.md
  Cargo.lock
  c_api/CHANGELOG.md
  c_api/Cargo.toml
  cawg_identity/CHANGELOG.md
  cawg_identity/Cargo.toml
  cli/CHANGELOG.md
  cli/Cargo.toml
  sdk/Cargo.toml
Labels: release

#1096 chore: release
  Cargo.lock
  cawg_identity/Cargo.toml
  cli/Cargo.toml
  internal/crypto/CHANGELOG.md
  internal/crypto/Cargo.toml
  sdk/Cargo.toml
Labels: release

#1097 chore: release
  CHANGELOG.md
  Cargo.lock
  c_api/Cargo.toml
  cawg_identity/Cargo.toml
  cli/CHANGELOG.md
  cli/Cargo.toml
  sdk/Cargo.toml
Labels: release

#1105 feat: Adds CAWG validation support to the c_api reader creation methods
  c_api/src/c_api.rs
Labels: safe to test

#1108 chore: release
  CHANGELOG.md
  Cargo.lock
  c_api/Cargo.toml
  cli/Cargo.toml
  internal/crypto/CHANGELOG.md
  internal/crypto/Cargo.toml
  sdk/Cargo.toml
Labels: release

#1110 chore: release
  Cargo.lock
  cli/CHANGELOG.md
  cli/Cargo.toml
  internal/crypto/Cargo.toml
Labels: release

#1119 chore(c2pa): release v0.53.0
  CHANGELOG.md
  Cargo.lock
  c_api/Cargo.toml
  cli/Cargo.toml
  sdk/Cargo.toml
Labels: release

#1121 chore(c2pa-status-tracker): release v0.7.0
  Cargo.lock
  internal/status-tracker/CHANGELOG.md
  internal/status-tracker/Cargo.toml
Labels: release

#1123 chore: release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  cli/CHANGELOG.md
  cli/Cargo.toml
Labels: release
