Repository contentauth/c2pa-rs, pull requests merged in 2025-09, with the labels that each got.

#1390 fix: assertion metadata localizations support was missing. CAI-9444
  sdk/src/assertions/assertion_metadata.rs
Labels: bug, safe to test, needs-doc

#1387 chore: remove the v1_api feature and all associated code
  Cargo.lock
  Makefile
  c2pa_c_ffi/Cargo.toml
  cli/Cargo.toml
  docs/usage.md
  make_test_images/Cargo.toml
  sdk/Cargo.toml
  sdk/src/builder.rs
  sdk/src/cose_sign.rs
  sdk/src/identity/identity_assertion/assertion.rs
  sdk/src/jumbf_io.rs
  sdk/src/lib.rs
  sdk/src/manifest.rs
  sdk/src/manifest_store.rs
  sdk/src/manifest_store_report.rs
  sdk/src/signer.rs
  sdk/src/store.rs
  sdk/src/utils/mime.rs
  sdk/src/utils/test.rs
  sdk/src/utils/test_signer.rs
  sdk/src/utils/thumbnail.rs
  sdk/src/validation_status.rs
  sdk/tests/integration.rs
  sdk/tests/test_builder.rs
Labels: release, needs-doc

#1391 chore: release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  c2pa_c_ffi/CHANGELOG.md
  c2pa_c_ffi/Cargo.toml
  cli/CHANGELOG.md
  cli/Cargo.toml
  make_test_images/Cargo.toml
Labels: release

#1419 chore: backport metadata fixes
  sdk/src/assertions/metadata.rs
  sdk/src/builder.rs
  sdk/src/claim.rs
  sdk/src/manifest.rs
  sdk/tests/test_builder.rs
Labels: safe to test, check-release

#1274 feat: add `ParametersMap` to `Actions`
  sdk/src/assertions/actions.rs
  sdk/src/assertions/mod.rs
  sdk/src/builder.rs
  sdk/src/claim.rs
  sdk/src/settings/builder.rs
  sdk/src/utils/cbor_types.rs
Labels: safe to test, needs-doc

#1428 feat: allow specifying external binary manifest to `c2patool`
  cli/src/main.rs
Labels: safe to test

#1421 chore: release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  c2pa_c_ffi/CHANGELOG.md
  c2pa_c_ffi/Cargo.toml
  cli/CHANGELOG.md
  cli/Cargo.toml
  make_test_images/Cargo.toml
Labels: release

#1440 fix: only enable "asm" feature on aarch64 macos
  sdk/Cargo.toml
Labels: check-release

#1452 ci: fix pdf benchmarks
  sdk/benches/fixtures/100kb-signed.pdf
  sdk/benches/fixtures/100kb.pdf
  sdk/benches/read.rs
  sdk/benches/sign.rs
Labels: safe to test

#1456 fix: Fix ARM builds
  .github/workflows/library-release.yml
  c2pa_c_ffi/Makefile
  make_release.ps1
Labels: safe to test, check-release

#1459 fix: allActionsIncluded defaults to None
  cli/tests/fixtures/trust/cawg_sign_settings.toml
  sdk/examples/c2pa.toml
  sdk/src/assertions/actions.rs
  sdk/src/builder.rs
  sdk/src/settings/builder.rs
  sdk/tests/fixtures/test_settings.toml
  sdk/tests/fixtures/test_settings_with_cawg_signing.toml
  sdk/tests/known_good/CA_test.json
  sdk/tests/test_builder.rs
Labels: safe to test, check-release
